"""Test templates for various frameworks."""

from .pytest_templates import (
    PYTEST_UNIT_TEMPLATE,
    PYTEST_FIXTURE_TEMPLATE,
    PYTEST_PROPERTY_TEMPLATE,
    PYTEST_INTEGRATION_TEMPLATE,
)
from .jest_templates import (
    JEST_UNIT_TEMPLATE,
    JEST_MOCK_TEMPLATE,
    JEST_INTEGRATION_TEMPLATE,
)

__all__ = [
    "PYTEST_UNIT_TEMPLATE",
    "PYTEST_FIXTURE_TEMPLATE",
    "PYTEST_PROPERTY_TEMPLATE",
    "PYTEST_INTEGRATION_TEMPLATE",
    "JEST_UNIT_TEMPLATE",
    "JEST_MOCK_TEMPLATE",
    "JEST_INTEGRATION_TEMPLATE",
]
